version: '3.8'

services:
  app:
    build: .
    container_name: sonorus-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./audios:/app/audios
      - ./pretrained_models:/app/pretrained_models
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: sonorus-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/backend/database/scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: